from __future__ import annotations

from pathlib import PurePosixPath
from typing import Any


class DocumentationScaffoldError(ValueError):
    pass


def _md(value: Any) -> str:
    return str(value or "").replace("|", r"\|").strip()


def _line_range(metadata: dict[str, Any]) -> str:
    start = metadata.get("line_start")
    end = metadata.get("line_end")
    if not start:
        return ""
    return str(start) if not end or end == start else f"{start}–{end}"


def entity_scaffold(entity: dict[str, Any], dependencies: dict[str, Any]) -> str:
    metadata = dict(entity.get("metadata") or {})
    name = _md(entity.get("qualified_name") or entity.get("name") or entity.get("id"))
    source_path = _md(entity.get("path"))
    lines = _line_range(metadata)
    signature = _md(metadata.get("signature"))
    docstring = str(metadata.get("docstring") or "").strip()
    outgoing = dependencies.get("outgoing") or []
    incoming = dependencies.get("incoming") or []

    body = [
        f"# `{name}`",
        "",
        "> Generated by PAH from deterministic CodeAnalyzer metadata. Review and complete the prose before publishing.",
        "",
        "## Purpose",
        "",
        docstring or "_Describe the responsibility of this code entity._",
        "",
        "## Location",
        "",
        f"- **File:** `{source_path}`",
    ]
    if lines:
        body.append(f"- **Lines:** {lines}")
    if signature:
        body.extend([f"- **Signature:** `{signature}`"])

    body.extend(["", "## Relationships", "", "### Calls / Uses", ""])
    if outgoing:
        for row in outgoing:
            other = row.get("other") or {}
            label = _md(other.get("qualified_name") or other.get("name") or other.get("id"))
            body.append(f"- `{label}` — {row.get('relationship_type', 'relationship')}")
    else:
        body.append("- _No outgoing analyzer relationships detected._")

    body.extend(["", "### Used By", ""])
    if incoming:
        for row in incoming:
            other = row.get("other") or {}
            label = _md(other.get("qualified_name") or other.get("name") or other.get("id"))
            body.append(f"- `{label}` — {row.get('relationship_type', 'relationship')}")
    else:
        body.append("- _No incoming analyzer relationships detected._")

    body.extend([
        "",
        "## Implementation Notes",
        "",
        "_Explain important assumptions, algorithms, invariants, or failure modes._",
        "",
        "## Related Documentation",
        "",
        "_Link architecture diagrams, experiments, papers, or neighboring modules here._",
        "",
    ])
    return "\n".join(body)


def file_scaffold(path: str, entities: list[dict[str, Any]]) -> str:
    title = PurePosixPath(path).name
    body = [
        f"# `{title}`",
        "",
        f"**Source:** `{path}`",
        "",
        "> Generated by PAH from CodeAnalyzer structure. This is a documentation scaffold, not an inferred behavioral specification.",
        "",
        "## Responsibility",
        "",
        "_Describe what this module/file owns._",
        "",
        "## Entities",
        "",
        "| Entity | Type | Signature | Lines |",
        "|---|---|---|---:|",
    ]
    for entity in entities:
        metadata = dict(entity.get("metadata") or {})
        body.append(
            f"| `{_md(entity.get('qualified_name') or entity.get('name'))}` | "
            f"{_md(entity.get('node_type'))} | `{_md(metadata.get('signature'))}` | {_line_range(metadata)} |"
        )
    if not entities:
        body.append("| _No analyzed entities_ | | | |")
    body.extend([
        "",
        "## Data / Control Flow",
        "",
        "_Describe how callers, dependencies, and state move through this file._",
        "",
        "## Maintenance Notes",
        "",
        "_Record constraints, extension points, and known technical debt._",
        "",
    ])
    return "\n".join(body)


def project_scaffold(overview: dict[str, Any], functions: list[dict[str, Any]]) -> str:
    summary = dict(overview.get("summary") or {})
    name = str(overview.get("project_name") or "Project")
    body = [
        f"# {name} — Technical Overview",
        "",
        "> Generated by PAH from deterministic repository analysis. Complete the descriptive sections manually.",
        "",
        "## Project Purpose",
        "",
        "_Describe the problem this project solves and its intended users._",
        "",
        "## Structural Summary",
        "",
        f"- Python files: {summary.get('python_files', 0)}",
        f"- Modules: {summary.get('modules', 0)}",
        f"- Classes: {summary.get('classes', 0)}",
        f"- Functions: {summary.get('functions', 0)}",
        f"- Methods: {summary.get('methods', 0)}",
        f"- Relationships: {summary.get('relationships', 0)}",
        f"- Internal imports: {summary.get('internal_imports', 0)}",
        f"- External imports: {summary.get('external_imports', 0)}",
        "",
        "## Architecture",
        "",
        "_Summarize the major subsystems. Use PAH's analyzer → diagram workflow to create editable dependency diagrams where useful._",
        "",
        "## Key Code Entities",
        "",
        "| Entity | File | Lines |",
        "|---|---|---:|",
    ]
    for entity in functions[:50]:
        metadata = dict(entity.get("metadata") or {})
        body.append(
            f"| `{_md(entity.get('qualified_name') or entity.get('name'))}` | "
            f"`{_md(entity.get('path'))}` | {_line_range(metadata)} |"
        )
    if len(functions) > 50:
        body.append(f"\n_Only the first 50 of {len(functions)} function/method entities are listed here._")
    body.extend([
        "",
        "## Similarity / Duplication Notes",
        "",
        "_Run repository similarity and duplicate analysis, then summarize findings that matter for maintenance._",
        "",
        "## Development and Execution",
        "",
        "_Document environment setup, entry points, tests, and common commands._",
        "",
        "## Research / References",
        "",
        "_If this project supports research, link papers and citations managed through PAH's ReferenceManager integration._",
        "",
    ])
    return "\n".join(body)
